// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'hardcoded_strings.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

HardcodedStrings _$HardcodedStringsFromJson(Map<String, dynamic> json) {
  return HardcodedStrings(
    matches: json['matches'] as String,
    newGame: json['newGame'] as String,
    quickActions: json['quickActions'] as String,
    lastTenMatches: json['lastTenMatches'] as String,
    statistics: json['statistics'] as String,
    history: json['history'] as String,
    leagues: json['leagues'] as String,
    pricing: json['pricing'] as String,
    settings: json['settings'] as String,
    about: json['about'] as String,
    logout: json['logout'] as String,
    language: json['language'] as String,
    darkTheme: json['darkTheme'] as String,
    lightTheme: json['lightTheme'] as String,
    changePassword: json['changePassword'] as String,
    enableNotifications: json['enableNotifications'] as String,
    common: json['common'] as String,
    security: json['security'] as String,
    won: json['won'] as String,
    lost: json['lost'] as String,
    scored: json['scored'] as String,
    recieved: json['recieved'] as String,
    goals: json['goals'] as String,
    user: json['user'] as String,
    username: json['username'] as String,
    organisation: json['organisation'] as String,
    personalInformation: json['personalInformation'] as String,
    integration: json['integration'] as String,
    slack: json['slack'] as String,
    discord: json['discord'] as String,
    matchDetails: json['matchDetails'] as String,
    totalPlayingTime: json['totalPlayingTime'] as String,
    newMatch: json['newMatch'] as String,
    rematch: json['rematch'] as String,
    twoPlayers: json['twoPlayers'] as String,
    fourPlayers: json['fourPlayers'] as String,
    choosePlayers: json['choosePlayers'] as String,
    match: json['match'] as String,
    startGame: json['startGame'] as String,
    chooseTeammate: json['chooseTeammate'] as String,
    chooseOpponent: json['chooseOpponent'] as String,
    chooseOpponents: json['chooseOpponents'] as String,
    matchReport: json['matchReport'] as String,
    game: json['game'] as String,
  );
}

Map<String, dynamic> _$HardcodedStringsToJson(HardcodedStrings instance) =>
    <String, dynamic>{
      'matches': instance.matches,
      'newGame': instance.newGame,
      'quickActions': instance.quickActions,
      'lastTenMatches': instance.lastTenMatches,
      'statistics': instance.statistics,
      'history': instance.history,
      'leagues': instance.leagues,
      'pricing': instance.pricing,
      'settings': instance.settings,
      'about': instance.about,
      'logout': instance.logout,
      'language': instance.language,
      'darkTheme': instance.darkTheme,
      'lightTheme': instance.lightTheme,
      'changePassword': instance.changePassword,
      'enableNotifications': instance.enableNotifications,
      'common': instance.common,
      'security': instance.security,
      'won': instance.won,
      'lost': instance.lost,
      'scored': instance.scored,
      'recieved': instance.recieved,
      'goals': instance.goals,
      'user': instance.user,
      'username': instance.username,
      'organisation': instance.organisation,
      'personalInformation': instance.personalInformation,
      'integration': instance.integration,
      'slack': instance.slack,
      'discord': instance.discord,
      'matchDetails': instance.matchDetails,
      'totalPlayingTime': instance.totalPlayingTime,
      'newMatch': instance.newMatch,
      'rematch': instance.rematch,
      'twoPlayers': instance.twoPlayers,
      'fourPlayers': instance.fourPlayers,
      'choosePlayers': instance.choosePlayers,
      'match': instance.match,
      'startGame': instance.startGame,
      'chooseTeammate': instance.chooseTeammate,
      'chooseOpponent': instance.chooseOpponent,
      'chooseOpponents': instance.chooseOpponents,
      'matchReport': instance.matchReport,
      'game': instance.game,
    };
